name: Modify Version

on:
  push:
    branches: [main]

jobs:
  modify_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: |
        sudo apt-get update -y
        sudo apt-get install -y jq

    - name: Modify Version
      run: |
        # Use jq to update the 'version' property in vss-extension.json
        jq '.version = "1.1.0"' vss-extension.json > vss-extension-modified.json

        # Move the modified file back to the original filename
        mv vss-extension-modified.json vss-extension.json

        # Display the modified file for verification
        cat vss-extension.json

    - name: Commit and Push Changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add vss-extension.json
        git commit -m "Update version in vss-extension.json"
        git push
