on:
  push:
    branches:
      - main

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
  
      - name: Install tfx-cli
        run: npm install -g tfx-cli
  
      - name: Install Dependencies
        run: npm install  # Assuming you have package.json with required dependencies

        
      - run: npm install
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: wldcm3wdhk4bljrzoou7w27sjsvdqgfkgigyq45f22suwlzpxksq
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ./TestGithubActions/vss-extension.json
          packagePath: ./TestGithubActions/vss-extension.json
