name: Build and Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_extension:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Print Workspace Path
      run: echo "${{ github.workspace }}"
      
    - name: set config
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
    - name: List Repository Files
      run: ls -R

    - name: Print Workspace Path
      run: echo "${{ github.workspace }}"
      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install tfx-cli
      run: |
        npm install -g tfx-cli
        git add .
      working-directory: ${{ github.workspace }}

    - name: Print Workspace Path
      run: echo "${{ github.workspace }}"

    - name: Build Extension
      run: |
        tfx extension create --manifest-globs vss-extension.json --output-path ${{ github.workspace }}
      working-directory: ${{ github.workspace }}


    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Build and publish extension"
        git push origin main
