name: Build and Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install tfx-cli
        run: |
          npm install -g tfx-cli
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          
      - name: Build Extension
        run: |
          tfx extension create --manifest-globs vss-extension.json
          
      - name: Get Current Version
        id: get_version
        run: echo "::set-output name=version::$(jq -r '.version' package.json)"

      - name: Increment Version
        run: |
          incremented_version=$(echo "${{ steps.get_version.outputs.version }}" | awk -F. '{print $1"."$2"."$3+1}')
          
      - name: Publish to Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: |
          tfx extension publish --token $VSCE_TOKEN
          jq --arg incremented_version "$incremented_version" '.version = $incremented_version' vss-extension.json> vss-extension.json-modified.json
          mv vss-extension.json-modified.json vss-extension.json
          cat vss-extension.json
